name: laravel-app

services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: pass
  composer:
    image: composer
    container_name: laravel-composer
    volumes:
      - ./:/app
    entrypoint: ["composer",]
  php: &base_php
    build:
      context: .
      dockerfile: Dockerfile
    image: base-php
    container_name: laravel-php
    volumes:
      - ./:/var/www/html
    entrypoint: ["php",]
  serve:
    <<: *base_php
    container_name: laravel-app
    ports:
      - '8000:8000'
    entrypoint: ["php", "artisan", "serve", "--host=0.0.0.0"]